[project]
name = "scratchi"
version = "0.1.0"
description = "Agentic Scratch Paper"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.10"
authors = [
    {name = "Taylor Cochran", email = "tcochran.dev@gmail.com"},
]

dependencies = [
]

[project.optional-dependencies]
dev = [
]
